databaseChangeLog:
  - changeSet:
      id: 2025021700
      author: poodingia
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addColumn:
            columns:
              - column:
                  name: status
                  type: VARCHAR(255)
            tableName: feedbacks