spring:
  application:
    name: order
  config:
    import: optional:consul:localhost:8500
  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.value}
  datasource:
    driverClassname: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order?user=keycloak&password=keycloak
  liquibase:
    change-log: classpath:config/liquibase/master_changelog.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 5
        order_inserts: true
    database: postgresql
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/ticketnow/protocol/openid-connect/certs


server:
  port: 8083

logging:
    level:
        root: INFO
        com.ticketnow.order: DEBUG
        org.springframework.web: ERROR