spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.value}
    gateway:
      default-filters:
      routes:
        - id: crud
          uri: lb://crud
          predicates:
            - Path=/api/crud/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay=
        - id: account
          uri: lb://account
          predicates:
            - Path=/api/account/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay=
        - id: feedback
          uri: lb://account
          predicates:
            - Path=/api/feedback/**, /api/follow/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay=
        - id: search
          uri: lb://search
          predicates:
            - Path=/api/search/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay=
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/order/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay=
        - id: nextjs
          uri: http://localhost:3000
          predicates:
              - Path=/**

  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:8080/realms/ticketnow
        registration:
          gateway:
            provider: keycloak
            client-id: gateway
            client-secret: o6NQRwVbuF5VM8iPf3LsYKKlC1MShtiy
            authorization-grant-type: authorization_code
            scope: openid, profile, email, roles
server:
  port: 28080

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.cloud.gateway: DEBUG
