spring:
  application:
        name: crud
  cloud:
      consul:
        enabled: true
        host: localhost
        port: 8500
        discovery:
            prefer-ip-address: true
            instance-id: ${spring.application.name}:${random.value}
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crud?user=keycloak&password=keycloak
  liquibase:
    change-log: classpath:config/liquibase/master_changelog.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true

    database: postgresql
  security:
    oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: http://localhost:8080/realms/ticketnow/protocol/openid-connect/certs

server:
  port: 8081


logging:
  level:
    root: INFO
    com.ticketnow.crud: DEBUG
    org.springframework.web: ERROR

