databaseChangeLog:
  - changeSet:
      id: 1741401144982-1
      author: poodingia
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - dropColumn:
            columnName: owner_id
            tableName: tickets
  - changeSet:
      id: 1741401144982-2
      author: poodingia
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addColumn:
            columns:
              - column:
                  name: owner_id
                  type: VARCHAR(255)
            tableName: tickets

